<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>kapua-assembly</artifactId>
        <groupId>org.eclipse.kapua</groupId>
        <version>1.6.12</version>
    </parent>

    <packaging>pom</packaging>
    <artifactId>kapua-assembly-api</artifactId>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-assembly-java-base</artifactId>
            <type>pom</type>
        </dependency>

        <!-- REST api dependency -->
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-rest-api-web</artifactId>
            <type>war</type>
        </dependency>

        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-locator-guice</artifactId>
        </dependency>
        <dependency>
            <groupId>aopalliance</groupId>
            <artifactId>aopalliance</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-commons</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-message-internal</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-account-internal</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-datastore-internal</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-security-shiro</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-device-registry-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-device-registry-internal</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-user-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-user-internal</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-security-certificate-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-security-certificate-internal</artifactId>
        </dependency>

        <!-- Runtime dependencies -->
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-device-management-all-api</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-device-management-all-internal</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-translator-kapua-kura</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-translator-kura-jms</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-translator-kura-mqtt</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-transport-api</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-transport-jms</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.eclipse.kapua</groupId>
            <artifactId>kapua-transport-mqtt</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- Other dependencies -->
        <dependency>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.eclipse.persistence</groupId>
            <artifactId>javax.persistence</artifactId>
        </dependency>
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-configuration</groupId>
            <artifactId>commons-configuration</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-core</artifactId>
        </dependency>
        <dependency>
            <groupId>io.dropwizard.metrics</groupId>
            <artifactId>metrics-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </dependency>
        <dependency>
            <groupId>org.javassist</groupId>
            <artifactId>javassist</artifactId>
        </dependency>
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jolokia</groupId>
            <artifactId>jolokia-jvm</artifactId>
            <version>${jolokia-jvm.version}</version>
            <classifier>agent</classifier>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-core</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>log4j-over-slf4j</artifactId>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <id>kapua-api</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                        <configuration>
                            <descriptors>
                                <descriptor>${project.basedir}/descriptors/kapua-api-jetty.xml</descriptor>
                            </descriptors>
                            <tarLongFileMode>posix</tarLongFileMode>
                            <finalName>kapua-api-${project.version}</finalName>
                            <appendAssemblyId>false</appendAssemblyId>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>release</id>
            <properties>
                <timestamp>latest</timestamp>
            </properties>
        </profile>
        <profile>
            <id>docker</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.fabric8</groupId>
                        <artifactId>docker-maven-plugin</artifactId>
                        <configuration>
                            <images>
                                <image>
                                    <name>${docker.account}/kapua-api</name>
                                    <build>
                                        <assembly>
                                            <descriptor>${project.basedir}/descriptors/kapua-api-jetty.xml</descriptor>
                                            <mode>tgz</mode>
                                            <tarLongFileMode>posix</tarLongFileMode>
                                        </assembly>
                                        <dockerFile>${project.basedir}/docker/Dockerfile</dockerFile>
                                        <filter>@</filter>
                                    </build>
                                </image>
                            </images>
                        </configuration>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>


<!--<?xml version="1.0" encoding="UTF-8"?>-->
<!--&lt;!&ndash;-->
<!--    Copyright (c) 2016, 2022 Eurotech and/or its affiliates and others-->

<!--    This program and the accompanying materials are made-->
<!--    available under the terms of the Eclipse Public License 2.0-->
<!--    which is available at https://www.eclipse.org/legal/epl-2.0/-->

<!--    SPDX-License-Identifier: EPL-2.0-->

<!--    Contributors:-->
<!--        Eurotech - initial API and implementation-->
<!--        Red Hat Inc-->
<!-- &ndash;&gt;-->
<!--<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">-->

<!--    <modelVersion>4.0.0</modelVersion>-->
<!--    <parent>-->
<!--        <artifactId>kapua-assembly</artifactId>-->
<!--        <groupId>org.eclipse.kapua</groupId>-->
<!--        <version>1.6.12</version>-->
<!--    </parent>-->

<!--    <packaging>pom</packaging>-->
<!--    <artifactId>kapua-assembly-api</artifactId>-->

<!--    <properties>-->
<!--        <nodejs.version>10.16.3</nodejs.version>-->
<!--        <swagger-cli.executable>${project.build.directory}/bin/swagger-cli</swagger-cli.executable>-->
<!--        <swagger-cli.version>4.0.4</swagger-cli.version>-->
<!--    </properties>-->

<!--    <dependencies>-->

<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-assembly-java-base</artifactId>-->
<!--            <type>pom</type>-->
<!--        </dependency>-->

<!--        &lt;!&ndash; REST api dependency &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-rest-api-web</artifactId>-->
<!--            <type>war</type>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-locator-guice</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>aopalliance</groupId>-->
<!--            <artifactId>aopalliance</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-commons</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-message-internal</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-account-internal</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-datastore-internal</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-security-shiro</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-device-registry-api</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-device-registry-internal</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-user-api</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-user-internal</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-security-certificate-api</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-security-certificate-internal</artifactId>-->
<!--        </dependency>-->

<!--        &lt;!&ndash; dependencies added otherwise the unix assembly doesn't know the artifact to add &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-device-management-all-api</artifactId>-->
<!--            <scope>runtime</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-device-management-all-internal</artifactId>-->
<!--            <scope>runtime</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-translator-kapua-kura</artifactId>-->
<!--            <scope>runtime</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-translator-kura-jms</artifactId>-->
<!--            <scope>runtime</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-translator-kura-mqtt</artifactId>-->
<!--            <scope>runtime</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-transport-api</artifactId>-->
<!--            <scope>runtime</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-transport-jms</artifactId>-->
<!--            <scope>runtime</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.eclipse.kapua</groupId>-->
<!--            <artifactId>kapua-transport-mqtt</artifactId>-->
<!--            <scope>runtime</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            &lt;!&ndash; Google protobuf for message encoding &ndash;&gt;-->
<!--            <groupId>com.google.protobuf</groupId>-->
<!--            <artifactId>protobuf-java</artifactId>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>org.eclipse.persistence</groupId>-->
<!--            <artifactId>javax.persistence</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.google.guava</groupId>-->
<!--            <artifactId>guava</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>commons-configuration</groupId>-->
<!--            <artifactId>commons-configuration</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.springframework.security</groupId>-->
<!--            <artifactId>spring-security-core</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>io.dropwizard.metrics</groupId>-->
<!--            <artifactId>metrics-core</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.reflections</groupId>-->
<!--            <artifactId>reflections</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.javassist</groupId>-->
<!--            <artifactId>javassist</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>commons-io</groupId>-->
<!--            <artifactId>commons-io</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.apache.commons</groupId>-->
<!--            <artifactId>commons-lang3</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.liquibase</groupId>-->
<!--            <artifactId>liquibase-core</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.yaml</groupId>-->
<!--            <artifactId>snakeyaml</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jolokia</groupId>-->
<!--            <artifactId>jolokia-jvm</artifactId>-->
<!--            <version>${jolokia-jvm.version}</version>-->
<!--            <classifier>agent</classifier>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>ch.qos.logback</groupId>-->
<!--            <artifactId>logback-core</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>ch.qos.logback</groupId>-->
<!--            <artifactId>logback-classic</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.slf4j</groupId>-->
<!--            <artifactId>log4j-over-slf4j</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.h2database</groupId>-->
<!--            <artifactId>h2</artifactId>-->
<!--        </dependency>-->
<!--        &lt;!&ndash; Swagger UI &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.webjars</groupId>-->
<!--            <artifactId>swagger-ui</artifactId>-->
<!--        </dependency>-->
<!--    </dependencies>-->

<!--    <build>-->
<!--        <plugins>-->
<!--&lt;!&ndash;            <plugin>&ndash;&gt;-->
<!--&lt;!&ndash;                <groupId>com.github.eirslett</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;                <artifactId>frontend-maven-plugin</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;                <executions>&ndash;&gt;-->
<!--&lt;!&ndash;                    <execution>&ndash;&gt;-->
<!--&lt;!&ndash;                        <id>install-node-and-npm</id>&ndash;&gt;-->
<!--&lt;!&ndash;                        <goals>&ndash;&gt;-->
<!--&lt;!&ndash;                            <goal>install-node-and-npm</goal>&ndash;&gt;-->
<!--&lt;!&ndash;                        </goals>&ndash;&gt;-->
<!--&lt;!&ndash;                    </execution>&ndash;&gt;-->
<!--&lt;!&ndash;                    <execution>&ndash;&gt;-->
<!--&lt;!&ndash;                        <id>install-swagger-cli</id>&ndash;&gt;-->
<!--&lt;!&ndash;                        <goals>&ndash;&gt;-->
<!--&lt;!&ndash;                            <goal>npm</goal>&ndash;&gt;-->
<!--&lt;!&ndash;                        </goals>&ndash;&gt;-->
<!--&lt;!&ndash;                        <configuration>&ndash;&gt;-->
<!--&lt;!&ndash;                            <arguments>install -g @apidevtools/swagger-cli@${swagger-cli.version}</arguments>&ndash;&gt;-->
<!--&lt;!&ndash;                        </configuration>&ndash;&gt;-->
<!--&lt;!&ndash;                    </execution>&ndash;&gt;-->
<!--&lt;!&ndash;                </executions>&ndash;&gt;-->
<!--&lt;!&ndash;                <configuration>&ndash;&gt;-->
<!--&lt;!&ndash;                    <nodeVersion>v${nodejs.version}</nodeVersion>&ndash;&gt;-->
<!--&lt;!&ndash;                    <installDirectory>target</installDirectory>&ndash;&gt;-->
<!--&lt;!&ndash;                </configuration>&ndash;&gt;-->
<!--&lt;!&ndash;            </plugin>&ndash;&gt;-->
<!--&lt;!&ndash;            <plugin>&ndash;&gt;-->
<!--&lt;!&ndash;                <groupId>org.apache.maven.plugins</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;                <artifactId>maven-dependency-plugin</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;                <executions>&ndash;&gt;-->
<!--&lt;!&ndash;                    <execution>&ndash;&gt;-->
<!--&lt;!&ndash;                        <id>unpack-swagger-ui</id>&ndash;&gt;-->
<!--&lt;!&ndash;                        <phase>prepare-package</phase>&ndash;&gt;-->
<!--&lt;!&ndash;                        <goals>&ndash;&gt;-->
<!--&lt;!&ndash;                            <goal>unpack</goal>&ndash;&gt;-->
<!--&lt;!&ndash;                        </goals>&ndash;&gt;-->
<!--&lt;!&ndash;                        <configuration>&ndash;&gt;-->
<!--&lt;!&ndash;                            <artifactItems>&ndash;&gt;-->
<!--&lt;!&ndash;                                <artifactItem>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <groupId>org.webjars</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <artifactId>swagger-ui</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <version>${swagger-ui.version}</version>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <overWrite>true</overWrite>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <outputDirectory>${project.build.directory}/tmp/swagger-ui</outputDirectory>&ndash;&gt;-->
<!--&lt;!&ndash;                                </artifactItem>&ndash;&gt;-->
<!--&lt;!&ndash;                            </artifactItems>&ndash;&gt;-->
<!--&lt;!&ndash;                        </configuration>&ndash;&gt;-->
<!--&lt;!&ndash;                    </execution>&ndash;&gt;-->
<!--&lt;!&ndash;                    <execution>&ndash;&gt;-->
<!--&lt;!&ndash;                        <id>unpack-openapi</id>&ndash;&gt;-->
<!--&lt;!&ndash;                        <phase>prepare-package</phase>&ndash;&gt;-->
<!--&lt;!&ndash;                        <goals>&ndash;&gt;-->
<!--&lt;!&ndash;                            <goal>unpack</goal>&ndash;&gt;-->
<!--&lt;!&ndash;                        </goals>&ndash;&gt;-->
<!--&lt;!&ndash;                        <configuration>&ndash;&gt;-->
<!--&lt;!&ndash;                            <artifactItems>&ndash;&gt;-->
<!--&lt;!&ndash;                                <artifactItem>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <groupId>org.eclipse.kapua</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <artifactId>kapua-rest-api-resources</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <version>${project.version}</version>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <overWrite>true</overWrite>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <outputDirectory>${project.build.directory}/tmp</outputDirectory>&ndash;&gt;-->
<!--&lt;!&ndash;                                    <includes>openapi/**/*</includes>&ndash;&gt;-->
<!--&lt;!&ndash;                                </artifactItem>&ndash;&gt;-->
<!--&lt;!&ndash;                            </artifactItems>&ndash;&gt;-->
<!--&lt;!&ndash;                        </configuration>&ndash;&gt;-->
<!--&lt;!&ndash;                    </execution>&ndash;&gt;-->
<!--&lt;!&ndash;                </executions>&ndash;&gt;-->
<!--&lt;!&ndash;            </plugin>&ndash;&gt;-->
<!--&lt;!&ndash;            <plugin>&ndash;&gt;-->
<!--&lt;!&ndash;                <groupId>org.codehaus.mojo</groupId>&ndash;&gt;-->
<!--&lt;!&ndash;                <artifactId>exec-maven-plugin</artifactId>&ndash;&gt;-->
<!--&lt;!&ndash;                <executions>&ndash;&gt;-->
<!--&lt;!&ndash;                    <execution>&ndash;&gt;-->
<!--&lt;!&ndash;                        <id>copy-openapi</id>&ndash;&gt;-->
<!--&lt;!&ndash;                        <goals>&ndash;&gt;-->
<!--&lt;!&ndash;                            <goal>exec</goal>&ndash;&gt;-->
<!--&lt;!&ndash;                        </goals>&ndash;&gt;-->
<!--&lt;!&ndash;                        <phase>prepare-package</phase>&ndash;&gt;-->
<!--&lt;!&ndash;                    </execution>&ndash;&gt;-->
<!--&lt;!&ndash;                </executions>&ndash;&gt;-->
<!--&lt;!&ndash;                <configuration>&ndash;&gt;-->
<!--&lt;!&ndash;                    <executable>${swagger-cli.executable}</executable>&ndash;&gt;-->
<!--&lt;!&ndash;                    <environmentVariables>&ndash;&gt;-->
<!--&lt;!&ndash;                        <PATH>$PATH:${project.build.directory}/node</PATH>&ndash;&gt;-->
<!--&lt;!&ndash;                    </environmentVariables>&ndash;&gt;-->
<!--&lt;!&ndash;                    <arguments>&ndash;&gt;-->
<!--&lt;!&ndash;                        <argument>bundle</argument>&ndash;&gt;-->
<!--&lt;!&ndash;                        <argument>-t</argument>&ndash;&gt;-->
<!--&lt;!&ndash;                        <argument>yaml</argument>&ndash;&gt;-->
<!--&lt;!&ndash;                        <argument>-o</argument>&ndash;&gt;-->
<!--&lt;!&ndash;                        <argument>${project.build.directory}/tmp/openapi.yaml</argument>&ndash;&gt;-->
<!--&lt;!&ndash;                        <argument>${project.build.directory}/tmp/openapi/openapi.yaml</argument>&ndash;&gt;-->
<!--&lt;!&ndash;                    </arguments>&ndash;&gt;-->
<!--&lt;!&ndash;                </configuration>&ndash;&gt;-->
<!--&lt;!&ndash;            </plugin>&ndash;&gt;-->
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-assembly-plugin</artifactId>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>kapua-api</id>-->
<!--                        <phase>package</phase>-->
<!--                        <goals>-->
<!--                            <goal>single</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <descriptors>-->
<!--                                <descriptor>${project.basedir}/descriptors/kapua-api-jetty.xml</descriptor>-->
<!--                            </descriptors>-->
<!--                            <tarLongFileMode>posix</tarLongFileMode>-->
<!--                            <finalName>kapua-api-${project.version}</finalName>-->
<!--                            <appendAssemblyId>false</appendAssemblyId>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->

<!--        </plugins>-->
<!--    </build>-->

<!--    <profiles>-->
<!--        <profile>-->
<!--            <id>release</id>-->
<!--            <properties>-->
<!--                <timestamp>latest</timestamp>-->
<!--            </properties>-->
<!--        </profile>-->
<!--        <profile>-->
<!--            <id>docker</id>-->
<!--            <build>-->
<!--                <plugins>-->
<!--                    <plugin>-->
<!--                        <groupId>io.fabric8</groupId>-->
<!--                        <artifactId>docker-maven-plugin</artifactId>-->
<!--                        <configuration>-->
<!--                            <images>-->
<!--                                <image>-->
<!--                                    <name>${docker.account}/kapua-api</name>-->
<!--                                    <build>-->
<!--                                        <assembly>-->
<!--                                            <descriptor>${project.basedir}/descriptors/kapua-api-jetty.xml</descriptor>-->
<!--                                            <mode>tgz</mode>-->
<!--                                            <tarLongFileMode>posix</tarLongFileMode>-->
<!--                                        </assembly>-->
<!--                                        <dockerFile>${project.basedir}/docker/Dockerfile</dockerFile>-->
<!--                                        <filter>@</filter>-->
<!--                                    </build>-->
<!--                                </image>-->
<!--                            </images>-->
<!--                        </configuration>-->
<!--                    </plugin>-->
<!--                </plugins>-->
<!--            </build>-->
<!--        </profile>-->
<!--        <profile>-->
<!--            <id>swagger-cli-windows</id>-->
<!--            <activation>-->
<!--                <os>-->
<!--                    <family>Windows</family>-->
<!--                </os>-->
<!--            </activation>-->
<!--            <properties>-->
<!--                <swagger-cli.executable>${project.build.directory}/node/swagger-cli.cmd</swagger-cli.executable>-->
<!--            </properties>-->
<!--        </profile>-->
<!--    </profiles>-->

<!--</project>-->
